# docker-compose.yml
version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
    command: python app.py
